### ISSUE TITLE
Do not write data to a file before sending to CKAN

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-dc-exporter#10]
In Jackan, we call the addBinaryBody version which accepts a file (https://github.com/opendatatrentino/jackan/blob/branch-0.4/src/main/java/eu/trentorise/opendata/jackan/CkanClient.java#L668). We could easily instead call the version that accepts a byte[].

**Comment by OtakuDigitChoc** [comment]
I made the changes on jackan but this project does not recompile, when I run dc-exporter project.

**Comment by bobeal** [comment]
Could you give me some details (what you did, what is the error) ?

**Comment by OtakuDigitChoc** [comment]
I modified this property : https://github.com/opendatatrentino/jackan/blob/branch-0.4/src/main/java/eu/trentorise/opendata/jackan/model/CkanResourceBase.java#L72 and all functions to receive a string. but in DC-exporter https://github.com/ozwillo/ozwillo-dc-exporter/blob/feature/3-v1-screen-of-mapping-from-DC-to-CKAN/src/main/java/org/ozwillo/dcexporter/service/CkanService.java#L131 the setUpload function always expects a File object.

**Comment by bobeal** [comment]
Did you redeploy Jackan in your local MVN repository ?
