### ISSUE TITLE
Error on field format when trying to create a new mapping

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-dc-exporter#14]
On branch feature/3-v1-screen-of-mapping-from-DC-to-CKAN

See screenshot for data entered in the configuration screen : 
![screen shot 2017-01-05 at 16 27 52](https://cloud.githubusercontent.com/assets/175382/21686042/22bd3a7a-d364-11e6-9686-2a69b2d76805.png)

Posted fields : 

```
{"resourceName":"Test resource adresses postales","name":"Adresses postales","description":"Description de ma ressource","license":"CC-BY-4.0","source":"Ozwillo","tags":[{"id":"da7dc07f-c2e5-46c9-9b23-1f953fed45e9","name":"tourisme"},{"id":"ed380c6e-ad22-4b57-ab53-32ede2819a62","name":"wifi"}],"dcId":"http://data.ozwillo.com/dc/type/dcmo:model_0/adrpost:Postal_0","type":"adrpost:Postal_0","project":"org_2"}
```

Error in the log : 

```
eu.trentorise.opendata.jackan.exceptions.CkanValidationException: Error while performing a POST! Request url is:https://opendata-preprod.data-ozwillo.org/api/3/action/package_create  CkanResponse{error=Ckan error of type: Validation Error  message:null  Other fields:{name=[Must be purely lowercase alphanumeric (ascii) characters and these symbols: -_]}, success=false, help=https://opendata-preprod.data-ozwillo.org/api/3/action/help_show?name=package_create}  CkanClient{catalogURL=https://opendata-preprod.data-ozwillo.org, ckanToken=*****MASKED_TOKEN*******}
        at eu.trentorise.opendata.jackan.CkanClient.throwCkanException(CkanClient.java:561)
        at eu.trentorise.opendata.jackan.CkanClient.postHttp(CkanClient.java:630)
        at eu.trentorise.opendata.jackan.CkanClient.createDataset(CkanClient.java:1523)
        at org.ozwillo.dcexporter.service.CkanService.getOrCreateDataset(CkanService.java:75)
        at org.ozwillo.dcexporter.controller.DcModelMappingController.addMapping(DcModelMappingController.java:30)
```

**Comment by OtakuDigitChoc** [comment]
CKAN does not accept spaces in the DATASET name

**Comment by OtakuDigitChoc** [comment]
@bobeal I can modify name before sending ?
for example : roll registration -> roll-registration

**Comment by bobeal** [comment]
Yes. Something like is done on CKAN itself so that the user knows how its dataset will be named (and can eventually act on it).

**Comment by OtakuDigitChoc** [comment]
I think it's better to put DC type in CKAN name.
for example : citizenkin:electoral_roll_registration_0

**Comment by bobeal** [comment]
Why not. Are ':', '_' and numbers authorized on CKAN ?

And if so, don't let users modify it in the app (or you'll have to enforce the naming rules).

**Comment by OtakuDigitChoc** [comment]
Finally when i create new dataset I format it, if dataset is existing the user can choose the old name formatted

**Comment by bobeal** [comment]
I still have an error with data shown in screenshot.
![screen shot 2017-01-17 at 16 19 18](https://cloud.githubusercontent.com/assets/175382/22026350/ca17b0f0-dcd0-11e6-9cfb-3ce406fc2c6a.png)

**Comment by OtakuDigitChoc** [comment]
The CKAN does not like accents, I thought about it.. I found a function that removes the accents
