### ISSUE TITLE
Design of audit logs screen

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-dc-exporter#18]

**Comment by franck-boucher** [comment]
The audit logs screen has been enhanced with the [Feature/34 view edit model mapping](https://github.com/ozwillo/ozwillo-dc-exporter/pull/40) merge.
Is it enough or do you have other improvements in mind ?

**Comment by bobeal** [comment]
For now, it is enough. We'll do a roadmap review after the next week demo.
