### ISSUE TITLE
Delete an existing mapping

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-dc-exporter#60]

**Comment by OtakuDigitChoc** [comment]
Run this mongo command before the 0.9.0 deployment : 
`db.getCollection('dcModelMapping').update({}, {$set: {"isDeleted": false}}, false, true)`

**Comment by bobeal** [comment]
Please put the migration notes in a wiki page (see for instance https://github.com/ozwillo/ozwillo-portal/wiki/Migration-notes)
