### ISSUE TITLE
See if the fields "dcmpv:name dcmpv:documentation" are not present or not entered for model in DC 

### ISSUE THREAD

**Issue by OtakuDigitChoc** [ozwillo/ozwillo-dc-exporter#7]

**Comment by bobeal** [comment]
Hi,

I had a look in the DC code : 

- The dcmo:name property is the model name so it does not give much information
- There is a dcmo:documentation property that does not seem to be really used (but you can check for its value in case there is something filled in it) ...

**Comment by OtakuDigitChoc** [comment]
thank's for this informations, but the content of dcmo: property isn't pertinent most of the time, for example : 

- "dcmo:documentation": "id = !pli:city + '/' + hash(id)"
- "dcmo:documentation": "id = !coita:atecoCode"
